-- Se ejecuta automaticamente la primera vez que Postgres arranca con un
-- volumen de datos vacio (mecanismo /docker-entrypoint-initdb.d/ de la
-- imagen oficial de postgres). El esquema coincide con las entidades JPA
-- de backend/src/main/java/.../infrastructure/persistence, asi que
-- Hibernate (ddl-auto: update) no necesita crear ni alterar nada al
-- arrancar el backend contra una base de datos ya inicializada con este
-- script.

CREATE TABLE IF NOT EXISTS pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mesa INTEGER NOT NULL,
    estado VARCHAR(20) NOT NULL,
    fecha_creacion TIMESTAMP,
    fecha_actualizacion TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lineas_pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_producto VARCHAR(255) NOT NULL,
    cantidad INTEGER NOT NULL,
    tipo_producto VARCHAR(20) NOT NULL,
    notas VARCHAR(255),
    pedido_id BIGINT REFERENCES pedidos(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_lineas_pedido_pedido_id ON lineas_pedido (pedido_id);
CREATE INDEX IF NOT EXISTS idx_pedidos_estado ON pedidos (estado);
